### PR TITLE
feat: implement sncrypto-node

### PR DESCRIPTION
**Pull request by standarius**
[Related task](https://app.asana.com/0/1199914526147392/1200062281509348/f)

### CODE REVIEW

**Comment by standarius** [comment]
- [x] Forgot to make the decrypt method return null when it fails.

**Comment by standarius** [comment]
>     * [ ]  Forgot to make the decrypt method return null when it fails.

Actually maybe I shouldn't do that and instead remove the null from the return type? What's the advantage?

**Review by atmoio — APPROVED** [review]
Very clean code 👌

**Comment by atmoio** [comment]
> Actually maybe I shouldn't do that and instead remove the null from the return type? What's the advantage?

What do you mean? It should either throw an exception or return null if decryption fails.

**Comment by standarius** [comment]
> > Actually maybe I shouldn't do that and instead remove the null from the return type? What's the advantage?
> 
> What do you mean? It should either throw an exception or return null if decryption fails.

Now it will throw an exception (nodejs will). Better than swallowing it an returning null IMO. So unless there is a good reason for the null, I'll go ahead and remove it.

**Comment by atmoio** [comment]
I guess we handle exceptions for the caller and return null in the web implementation: https://github.com/standardnotes/sncrypto/blob/004/packages/web/src/crypto.ts#L307

**Comment by standarius** [comment]
> I guess we handle exceptions for the caller and return null in the web implementation: https://github.com/standardnotes/sncrypto/blob/004/packages/web/src/crypto.ts#L307

Returning null isn't really handling it :P
It eats the exception and now the user has to figure out what this null means. If the library could have thrown n exceptions due to n different reasons they are all now flattened to a single null value.

Better to let the library throw and have the user deal with that than with a mystery.

**Comment by atmoio** [comment]
That's true. I guess I assumed there really could only be one reason decryption fails: wrong key. But it could be other things like wrong aad or something. But I don't think the encryption algos will tell you that anyway. So overall I'm not sure how many exceptions there are possibly, but you're right, may be better to bubble the exception than suppress it.

**Pull request merged**
