### PR TITLE
Refactors web related crypto into own namespace

### PR DESCRIPTION
**Pull request by atmoio**

### CODE REVIEW

**Comment by atmoio** [comment]
cc @radko93

**Review by radko93 — COMMENTED** [review]
This is definitely what we wanted, it would be even better if we could release those two parts separately. So webcrypto is not installed when you install snjs.
One more comment: if you have removed libsodium bundle and won't be including that anymore you need to have to in `dependencies` and not in `devDependencies` to ensure it's installed. But then it will be also installed on mobile which is not what we want.

**Comment by atmoio** [comment]
> So webcrypto is not installed when you install snjs.

Well as long as you don't import sncrypto-web in mobile it won't be installed right?

>  if you have removed libsodium bundle

Those bundle files were actually stale files and weren't used. Libsodium is now inside the sncrypto-web.js file.

**Comment by radko93** [comment]
> Well as long as you don't import sncrypto-web in mobile it won't be installed right?

Not sure if it will be in the production bundle but it will be downloaded as well.

**Comment by atmoio** [comment]
Yeah, it'll be downloaded via npm, but I'm sure there's a way to avoid it being in the app bundle. But this approach to single package makes it much simpler. We can do the multi package approach if absolutely necessary but just makes things a little tricker. We'd have to use something like [lerna](https://github.com/lerna/lerna).

**Pull request merged**
